# .streamlit/config.toml

[theme]

# Cor principal para elementos interativos
primaryColor="#4F8BF9"

# Cor de fundo principal da aplicação (Branco)
backgroundColor="#FFFFFF"

# Cor de fundo de elementos secundários (como a barra lateral)
secondaryBackgroundColor=""#cee8faff""

# Cor do texto principal (Preto)
textColor="#262730"

# Fonte a ser usada
font="sans serif"